import { createElement } from 'lwc';
import LAB_CustomLookUp_Assignment from 'c/lAB_CustomLookUp_Assignment';

describe('c-l-a-b-custom-look-up-assignment', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-a-b-custom-look-up-assignment', {
            is: LAB_CustomLookUp_Assignment
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});