import { createElement } from 'lwc';
import LDS_4_UIRecordDemo from 'c/lDS_4_UIRecordDemo';

describe('c-l-d-s-4-ui-record-demo', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-d-s-4-ui-record-demo', {
            is: LDS_4_UIRecordDemo
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});